Repository knowitrickard/FlexiCharge-iOS, pull requests merged in 2021-09, with the labels that each got.

#22 Create pull_request_template.md
  .github/pull_request_template.md
Labels: Enhancement ✨, Done

#36 Register account
  FlexiCharge/.DS_Store
  FlexiCharge/FlexiCharge.xcodeproj/project.pbxproj
  FlexiCharge/FlexiCharge/.DS_Store
  FlexiCharge/FlexiCharge/Assets.xcassets/.DS_Store
  FlexiCharge/FlexiCharge/Assets.xcassets/Combined Shape-1.svg
  FlexiCharge/FlexiCharge/Assets.xcassets/topShapeRegister.imageset/Combined Shape-1.svg
  FlexiCharge/FlexiCharge/Assets.xcassets/topShapeRegister.imageset/Contents.json
  FlexiCharge/FlexiCharge/FlexiChargeApp.swift
  FlexiCharge/FlexiCharge/Views/RegisterAccount/RegisterAccountView.swift
  FlexiCharge/FlexiCharge/Views/RegisterAccount/RegisterAccountViewModel.swift
Labels: Enhancement ✨

#57 Various design fixes. QoF
  FlexiCharge/FlexiCharge.xcodeproj/project.xcworkspace/xcuserdata/filipfloden.xcuserdatad/UserInterfaceState.xcuserstate
  FlexiCharge/FlexiCharge/Views/Content/ContentView.swift
  FlexiCharge/FlexiCharge/Views/IdentifyCharger/IdentifyChargerView.swift
  FlexiCharge/FlexiCharge/Views/Login/LoginView.swift
  FlexiCharge/FlexiCharge/Views/Map/MapView.swift
  FlexiCharge/FlexiCharge/Views/RecoverPassword/EmailSentView.swift
  FlexiCharge/FlexiCharge/Views/RecoverPassword/RecoverPasswordView.swift
  FlexiCharge/FlexiCharge/Views/RegisterAccount/RegisterAccountView.swift
Labels: Done

#61 Feat/invoices view
  FlexiCharge/FlexiCharge.xcodeproj/project.pbxproj
  FlexiCharge/FlexiCharge/Assets.xcassets/black-arrow.imageset/Contents.json
  FlexiCharge/FlexiCharge/Assets.xcassets/black-arrow.imageset/black-arrow.svg
  FlexiCharge/FlexiCharge/Views/Settings/Invoices/InvoicesView.swift
  FlexiCharge/FlexiCharge/Views/Settings/Invoices/InvoicesViewModel.swift
  FlexiCharge/FlexiCharge/Views/Settings/SetupInvoice/SetUpInvoiceView.swift
  FlexiCharge/FlexiCharge/Views/Settings/SetupInvoice/SetupUpInvoiceViewModel.swift
Labels: Bug 🐛, Enhancement ✨, Hotfix  🔥
